"""
Django settings for weather_monitor project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import os

load_dotenv()

# Defines project paths in the form: BASE_DIR / "subdir" due to settings now being a package, Inner project folder becomes the root dir
BASE_DIR = Path(__file__).resolve().parent.parent

# Project root urls
ROOT_URLCONF = 'weather_monitor.urls'

# WSGI
WSGI_APPLICATION = 'weather_monitor.wsgi.application'

# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Project Env managed
SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG_PROD') == 'True'

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS").split(",")

# Site Admins
ADMINS = [
    ("Site Owner", "weather_monitor-admin@weather_monitor.online")
]

# Application Definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    "whitenoise",
    "django_extensions",
    "health_check"
]

LOCAL_APPS = [
    # "example.apps.AccountsConfig",
    "accounts.apps.AccountsConfig",
    'weather.apps.WeatherConfig'
]

INSTALLED_APPS: list = [

]
INSTALLED_APPS += DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS
# --- End of Application Definition ---

# New Default User
AUTH_USER_MODEL = 'accounts.CustomUser'

# Project Middleware

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL_PROD"),
        conn_max_age=600,
        ssl_require=True,
    )
}

# Templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'weather_monitor/templates'],  # noqa
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # noqa
STATICFILES_DIRS = [
    BASE_DIR / "static",  # noqa
]

# Whitenoise config
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Health Check
# https://codingjoe.dev/django-health-check/
HEALTH_CHECK_TOKEN = os.getenv('HEALTH_CHECK_TOKEN')
